apiVersion: apps/v1
kind: Deployment
metadata:
  name: myApp-deployment
  labels:
    app: myApp
    type: front-end
spec:
  template:
    metadata:
      name: myApp-pod
      labels:
        app: myApp
        type: front-end
    spec:
      containers:
      - name: nginx
        image: nginx:1.9.1
  replicas: 3
  selector:
    matchLabels:
      type: front-end

